server:
  port: 8080

tolgee:
  front-end-url: http://localhost:8090
  authentication:
    enabled: ${TOLGEE_AUTHENTICATION_ENABLED}
    registrations-allowed: ${TOLGEE_AUTHENTICATION_REGISTRATIONS_ALLOWED}
    initial-username: ${TOLGEE_INITIAL_USERNAME}
    initial-password: ${TOLGEE_INITIAL_PASSWORD}
    jwt-secret: ${TOLGEE_JWT_SECRET}
