{
 "title": "CV API Overview",
 "tags": [
  "cv",
  "api",
  "observability"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RPS (overall)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[30s]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "Error rate (5xx)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[1m]))",
     "legendFormat": "5xx/s"
    }
   ]
  },
  {
   "title": "p95 latency (seconds)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[30s])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "CPU (process)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[30s])",
     "legendFormat": "cpu_seconds/s"
    }
   ]
  },
  {
   "title": "Memory (process RSS)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "rss_bytes" }
   ]
  },
  {
   "title": "API Logs (Loki)",
   "type": "logs",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "{job=\"docker-json-logs\"}"
    }
   ]
  },
  {
   "title": "API Logs (Only)",
   "type": "logs",
   "gridPos": { "x": 12, "y": 24, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "{job=\"docker-json-logs\", container_id=\"b0f3f47c4e50f192fcf27b5478c24bbae53b6515ecfc65c7546437787b5772d1\"}"
    }
   ]
  }
 ]
}