global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "platform-app-api"
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ["api.platform.example.com"]

rule_files:
  - /etc/prometheus/prometheus.rules.yml
  - /etc/prometheus/prometheus.alerts.yml
