global:
  scrape_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "cv-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["cv-app-local-api-1:3000"]
  - job_name: "gpool-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["gpool-app-local-api-1:3000"]

rule_files:
  - /etc/prometheus/prometheus.rules.yml
  - /etc/prometheus/prometheus.alerts.yml
